# Site settings
title: John Paz
subtitle: Content Designer
email: johnapaz@gmail.com
description: Just because you haven't heard of it, doesn't mean it's not awesome.
url: "https://johnapaz.com" # the base hostname & protocol for your site
author: John Paz
city: San Francisco
state: CA
country: USA
phone: (510) 707-7494

# Social settings
facebook_url: https://www.facebook.com/johnapaz/
github_url: https://github.com/johnapaz
gitlab_url: https://gitlab.com/johnapaz
instagram_url: https://www.instagram.com/techwriterninja/
linkedin_url: https://www.linkedin.com/in/johnapaz
twitter_url: https://twitter.com/SrContentDesign

# Build settings
markdown: kramdown
collections: 
  - about
  - reviews
  - tutorials
collections_dir: content
permalink: /:categories/:title:/

# Breadcrumbs
breadcrumbs:
  root:
    hide: true  # show breadcrumbs on root/home page
    image: false # Show image or title text